---
- name: Deploy a custom index.html with the hostname of the machine
  template: src=index.html.j2 dest=/var/www/html/index.html
 
- name: Download background images for index.html
  uri:
    url: https://github.com/MikeNald/ansible-tower-examples/blob/master/inteltour.png
    dest: /var/tmp/inteltour.png
  
- name: copy background images for index.html
  command: cp -p /var/tmp/inteltour.png /var/www/html/inteltour.png
   
