
- hosts: security

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_standard
    oscap_policy: ssg-rhel7-ds.xml
  become: true
  
  tasks:

  - name: create openscap remediation playbook based on profile 
    command: oscap xccdf generate fix \
        --fix-type ansible \
        --profile {{ oscap_profile }} \
        --output /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}
        
  - name: fix ansible_user on rhel-scap-standard-rhel7-role.yml file
    shell: sed -i '/"Fail if user is not root"/,+11d' /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml
      
  - name: fixing permission on output playbook
    file:
      path: /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml
      owner: mike
      group: mike
      mode: 0755
    
  - name: install git 
    yum:
      name: git
      state: present
       
  - name: accept ssh keys for git
    shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts
    
  - name: configure git push mode
    command: git config --global push.default simple
    
  - name: cloning git repo locally
    git:
     repo: https://github.com/MikeNald/ansible-tower-examples.git
     dest: /home/mike/ansible-tower-examples
     #key_file: /home/mike/.ssh/id_rsa
     accept_hostkey: yes
     force: yes  
  
  - name: fixing permission on git repo
    file:
      path: /home/mike/ansible-tower-examples
      owner: mike
      group: mike
      mode: 0755      
      recurse: yes
  
  - name: copy ansible playbook to local gitepo  folder
    copy:
     src: /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml
     dest: /home/mike/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml         
     remote_src: yes
     owner: mike
     group: mike
     mode: 0755
     
  - name: copying report to local git folder
    copy:
     src: /tmp/oscap-report.html
     dest: /home/mike/ansible-tower-examples/security/report/{{ inventory_hostname }}-scan-xccdf-report.html
     remote_src: yes
     owner: mike
     group: mike
     mode: 0755
    
      
  - name: replace target host with correct target  
    replace:
     path: /home/mike/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml
     regexp: '- hosts: all'
     replace: '- hosts: security' 
    
  - name: set permission for id_rsa private key
    file:
     path: /home/mike/.ssh/id_rsa
     owner: mike
     group: mike
     mode: 0600
     
  - name: add new playbook to git (git add)
    shell: cd /home/mike/ansible-tower-examples/; git add -f "{{ item }}"          
    with_items:
     - /home/mike/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml 
     - /home/mike/ansible-tower-examples/security/report/{{ inventory_hostname }}-scan-xccdf-report.html
    become_user: mike
  
  - name: git commit 
    shell: cd /home/mike/ansible-tower-examples/; git commit -m "add new playbook for fixing sec issue on host {{ inventory_hostname }}"
    
  - name: git push
    shell: cd /home/mike/ansible-tower-examples/; git push
    become_user: mike
   
#  - name: delete local git repo folder
#    command: rm -rf /home/ops/ansible-tower-examples/
    
#  - name: uninstall git
#    yum:
#      name: git
#      state: removed
