- hosts: oscap_target

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_standard
    oscap_policy: ssg-rhel7-ds.xml
  tasks:

  - name: create openscap remediation playbook
    command: oscap xccdf generate fix \
        --fix-type ansible \
        --profile {{ oscap_profile }} \
        --output /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}

   
  - name: download report
    fetch:
     src: /tmp/oscap-report.html
     dest: /oscap-reports/{{ inventory_hostname }}-scan-xccdf-report.html
     flat: yes
    
  - name: install git 
    yum:
      name: git
      state: present
       
  - name: accept ssh keys for git
    shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts
    
  - name: git repo config  
    command: git clone git@github.com:MikeNald/ansible-tower-examples.git /oscap-reports/ansible-tower-examples
    become: false
  #- name:  git username config
  #  command: git config user.name MikeNald \ 
  #         git config git remote set-url origin git@github.com:MikeNald/ansible-tower-examples.git
           
  - name: download ansible playbook
    fetch:
     src: /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml
     dest: /oscap-reports/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml
     flat: yes          
           
  - name: add new playbook to git
    command: git add /oscap-reports/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml          

  - name: git commit 
    command: git commit -m "add new playbook for fixing sec issue on host {{ inventory_hostname }}"

  - name: git push
    command: git push 
