- hosts: oscap_target

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_standard
    oscap_policy: ssg-rhel7-ds.xml
  become: true
  
  tasks:

  - name: create openscap remediation playbook based on profile 
    command: oscap xccdf generate fix \
        --fix-type ansible \
        --profile {{ oscap_profile }} \
        --output /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}
  
  - name: fixing permission on output playbook
    file:
      path: /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml
      owner: ops
      group: ops
      mode: 0755
    
  - name: install git 
    yum:
      name: git
      state: present
       
  - name: accept ssh keys for git
    shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts
    
  - name: cloning git repo locally
    git:
     repo: ssh://git@github.com/MikeNald/ansible-tower-examples.git
     dest: /home/ops/ansible-tower-examples
     key_file: /home/ops/.ssh/id_rsa
     accept_hostkey: yes
     force: yes  
  
  - name: fixing permission on git repo
    file:
      path: /home/ops/ansible-tower-examples
      owner: ops
      group: ops
      mode: 0755      
      recurse: yes
  
  - name: copy ansible playbook to local gitepo  folder
    copy:
     src: /tmp/{{ inventory_hostname }}-standard-rhel7-role.yml
     dest: /home/ops/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml         
     remote_src: yes
     owner: ops
     group: ops
     mode: 0755
     
  - name: copying report to local git folder
    copy:
     src: /tmp/oscap-report.html
     dest: /home/ops/ansible-tower-examples/security/report/{{ inventory_hostname }}-scan-xccdf-report.html
     remote_src: yes
     owner: ops
     group: ops
     mode: 0755
    
      
  - name: replace target host with correct target  
    replace:
     path: /home/ops/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml
     regexp: '- hosts: all'
     replace: '- hosts: oscap_target'   
     
  - name: avoiding usage of root account 
    replace:
     path: /home/ops/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml
     regexp: 'when: ansible_user != "root"|when: ansible_user == "root"'
     replace: '# old when condition' 
     
     
  - name: avoiding fail message 
    replace:
     path: /home/ops/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml
     regexp: '- name: "Fail if user is not root"|fail:|msg: 'Root account required to read root $PATH''
     replace: '' 
     
 
  - name: add new playbook to git 
    shell: cd /home/ops/ansible-tower-examples/; git add "{{ item }}"          
    with_items:
    - /home/ops/ansible-tower-examples/security/{{ inventory_hostname }}-standard-rhel7-role.yml 
    - /home/ops/ansible-tower-examples/security/report/{{ inventory_hostname }}-scan-xccdf-report.html  
    
  - name: git commit 
    shell: cd /home/ops/ansible-tower-examples/; git commit -m "add new playbook for fixing sec issue on host {{ inventory_hostname }}"

  - name: git push
    shell: cd /home/ops/ansible-tower-examples/; git push
    become_user: ops
   
#  - name: delete local git repo folder
#    command: rm -rf /home/ops/ansible-tower-examples/
    
#  - name: uninstall git
#    yum:
#      name: git
#      state: removed
